//
//  Product.swift
//  SwiftfulShopping
//
//  Created by Łukasz Janiszewski on 23/06/2022.
//

import Foundation

typealias ProductSpecification = [String: [SpecificationKeys: String]]

struct Product {
    var id: String
    var name: String
    var company: String
    var productDescription: String
    var category: Category
    var priceForCurrency: [String: Double]
    var specification: ProductSpecification
    var unitsSold: Int
    var introducedForSale: Date
    var isRecommended: Bool
    var isNew: Bool
    var keywords: [String]
    var productQuantityAvailable: Int
    var availability: Availability
    var imagesURLs: [String]
    
    var price: Double?
    
    init(id: String = UUID().uuidString,
         name: String,
         company: String,
         productDescription: String,
         category: Category,
         priceForCurrency: [String: Double],
         specification: ProductSpecification,
         unitsSold: Int = 0,
         introducedForSale: Date = Date(),
         isRecommended: Bool = false,
         isNew: Bool = true,
         keywords: [String] = [],
         productQuantityAvailable: Int,
         imagesURLs: [String] = [URLConstants.emptyProductPhoto]) {
        self.id = id
        self.name = name
        self.company = company
        self.productDescription = productDescription
        self.category = category
        self.priceForCurrency = priceForCurrency
        self.specification = specification
        self.unitsSold = unitsSold
        self.introducedForSale = introducedForSale
        self.isRecommended = isRecommended
        self.isNew = isNew
        if keywords.isEmpty {
            self.keywords = [name, company, category.decodeValue]
        } else {
            self.keywords = keywords + [name, company, category.decodeValue]
        }
        self.productQuantityAvailable = productQuantityAvailable
        
        switch productQuantityAvailable {
        case _ where productQuantityAvailable <= 0:
            availability = .no
        case _ where productQuantityAvailable > 0 && productQuantityAvailable < 20:
            availability = .small
        case _ where productQuantityAvailable >= 20:
            availability = .large
        default:
            availability = .no
        }
        
        self.imagesURLs = imagesURLs
        
        guard let currencyCode = LocaleManager.client.clientCurrencyCode, let price = priceForCurrency[currencyCode] else { return }
        self.price = price
    }
}

extension Product: Equatable, Hashable {
    static func == (lhs: Product, rhs: Product) -> Bool {
        return lhs.id == rhs.id
    }
    
    func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }
}

extension Product: CustomStringConvertible {
    var description: String {
        "\(id)\n\(name)\n\(company)\n\(productDescription)\n\(priceForCurrency)"
    }
}

extension Product {
    static let demoProducts: [Product] = [Product(id: "LQHU7yJplIXugoPiLucR",
                                                  name: "iPhone 13 Pro",
                                                  company: "Apple Inc.",
                                                  productDescription: "iPhone 13 Pro takes a huge leap forward, bringing incredible speed to everything you do and dramatic new photo and video capabilities — all in two great sizes.",
                                                  category: .phones,
                                                  priceForCurrency: ["USD": 799.99,
                                                                     "PLN": 3688.06,
                                                                     "CZK": 19112.45,
                                                                     "EUR": 787.08,
                                                                     "GBP": 686.21],
                                                  specification: [LanguageIdentifiers.english.rawValue: [SpecificationKeys.processor: "Apple A15 Bionic",
                                                                                                         SpecificationKeys.ramMemory: "4 GB",
                                                                                                         SpecificationKeys.massStorage: "256 GB",
                                                                                                         SpecificationKeys.displayType: "Touchable, OLED, Super Retina XDR, True Tone, Haptic Touch",
                                                                                                         SpecificationKeys.displaySize: "6.1\"",
                                                                                                         SpecificationKeys.displayResolution: "",
                                                                                                         SpecificationKeys.pixelDensity: "460 ppi",
                                                                                                         SpecificationKeys.refreshRate: "120 Hz",
                                                                                                         SpecificationKeys.displayBrightness: "",
                                                                                                         SpecificationKeys.cameraPhotoResolutionFront: "12.0 Mpix",
                                                                                                         SpecificationKeys.cameraPhotoResolutionBack: "12.0 Mpix - wide-angle, 12.0 Mpix - ultra wide-angle",
                                                                                                         SpecificationKeys.cameraZoomBack: "5x digital zoom",
                                                                                                         SpecificationKeys.cameraVideoResolutionBack: "UHD 4K (60 FPS)",
                                                                                                         SpecificationKeys.connectivity: "5G, Bluetooth 5.0, NFC, Wi-Fi",
                                                                                                         SpecificationKeys.inputs: "nanoSIM, Lightning",
                                                                                                         SpecificationKeys.fingerprintReader: "No",
                                                                                                         SpecificationKeys.faceReader: "Yes",
                                                                                                         SpecificationKeys.operatingSystem: "iOS 15",
                                                                                                         SpecificationKeys.weight: "",
                                                                                                         SpecificationKeys.additionalInfo: ""],
                                                                  
                                                                  LanguageIdentifiers.polish.rawValue: [SpecificationKeys.processor: "Apple A15 Bionic",
                                                                                                        SpecificationKeys.ramMemory: "4 GB",
                                                                                                        SpecificationKeys.massStorage: "256 GB",
                                                                                                        SpecificationKeys.displayType: "Dotykowy, OLED, Super Retina XDR, True Tone, Haptic Touch",
                                                                                                        SpecificationKeys.displaySize: "6.1\"",
                                                                                                        SpecificationKeys.displayResolution: "",
                                                                                                        SpecificationKeys.pixelDensity: "460 ppi",
                                                                                                        SpecificationKeys.refreshRate: "120 Hz",
                                                                                                        SpecificationKeys.displayBrightness: "",
                                                                                                        SpecificationKeys.cameraPhotoResolutionFront: "12.0 Mpix",
                                                                                                        SpecificationKeys.cameraPhotoResolutionBack: "12.0 Mpix - szerokokątny, 12.0 Mpix - ultraszerokokątny",
                                                                                                        SpecificationKeys.cameraZoomBack: "5x zoom cyfrowy",
                                                                                                        SpecificationKeys.cameraVideoResolutionBack: "UHD 4K (60 Klatek)",
                                                                                                        SpecificationKeys.connectivity: "5G, Bluetooth 5.0, NFC, Wi-Fi",
                                                                                                        SpecificationKeys.inputs: "nanoSIM, Lightning",
                                                                                                        SpecificationKeys.fingerprintReader: "Nie",
                                                                                                        SpecificationKeys.faceReader: "Tak",
                                                                                                        SpecificationKeys.operatingSystem: "iOS 15",
                                                                                                        SpecificationKeys.weight: "",
                                                                                                        SpecificationKeys.additionalInfo: ""]],
                                                  unitsSold: 220,
                                                  isRecommended: true,
                                                  keywords: ["telephone", "phone", "mobile phone", "iPhone", "mobile device"],
                                                  productQuantityAvailable: 200,
                                                  imagesURLs: ["https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-13-pro-max-green-select?wid=940&hei=1112&fmt=png-alpha&.v=1644969385495",
                                                               "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-13-pro-max-silver-select?wid=940&hei=1112&fmt=png-alpha&.v=1645552346280"]),
                                          Product(id: "mdQsy0eqYaSiKp6z393S",
                                                  name: "iPad Air",
                                                  company: "Apple Inc.",
                                                  productDescription: "iPad Air lets you immerse yourself in whatever you’re reading, watching, or creating. The 10.9-inch Liquid Retina display features advanced technologies like True Tone, P3 wide color, and an antireflective coating.",
                                                  category: .tablets,
                                                  priceForCurrency: ["USD": 599.99,
                                                                     "PLN": 2766.03,
                                                                     "CZK": 14334.27,
                                                                     "EUR": 590.31,
                                                                     "GBP": 514.65],
                                                  specification: [LanguageIdentifiers.english.rawValue: [SpecificationKeys.processor: "Apple M1 (8 cores, ARM)",
                                                                                                         SpecificationKeys.ramMemory: "8 GB",
                                                                                                         SpecificationKeys.massStorage: "64 GB",
                                                                                                         SpecificationKeys.displayType: "IPS, Liquid Retina",
                                                                                                         SpecificationKeys.displaySize: "10.9\"",
                                                                                                         SpecificationKeys.displayResolution: "",
                                                                                                         SpecificationKeys.pixelDensity: "",
                                                                                                         SpecificationKeys.refreshRate: "60 Hz",
                                                                                                         SpecificationKeys.displayBrightness: "",
                                                                                                         SpecificationKeys.cameraPhotoResolutionFront: "12.0 Mpix",
                                                                                                         SpecificationKeys.cameraPhotoResolutionBack: "12.0 Mpix",
                                                                                                         SpecificationKeys.cameraZoomBack: "",
                                                                                                         SpecificationKeys.cameraVideoResolutionBack: "UHD 4K (60 FPS)",
                                                                                                         SpecificationKeys.connectivity: "5G, Bluetooth, Wi-FI 6",
                                                                                                         SpecificationKeys.inputs: "nanoSIM, USB-C",
                                                                                                         SpecificationKeys.fingerprintReader: "Yes",
                                                                                                         SpecificationKeys.faceReader: "No",
                                                                                                         SpecificationKeys.operatingSystem: "iPadOS 15",
                                                                                                         SpecificationKeys.weight: "",
                                                                                                         SpecificationKeys.additionalInfo: ""],
                                                                  
                                                                  LanguageIdentifiers.polish.rawValue: [SpecificationKeys.processor: "Apple M1 (8 rdzeni, ARM)",
                                                                                                        SpecificationKeys.ramMemory: "8 GB",
                                                                                                        SpecificationKeys.massStorage: "64 GB",
                                                                                                        SpecificationKeys.displayType: "IPS, Liquid Retina",
                                                                                                        SpecificationKeys.displaySize: "10.9\"",
                                                                                                        SpecificationKeys.displayResolution: "",
                                                                                                        SpecificationKeys.pixelDensity: "",
                                                                                                        SpecificationKeys.refreshRate: "60 Hz",
                                                                                                        SpecificationKeys.displayBrightness: "",
                                                                                                        SpecificationKeys.cameraPhotoResolutionFront: "12.0 Mpix",
                                                                                                        SpecificationKeys.cameraPhotoResolutionBack: "12.0 Mpix",
                                                                                                        SpecificationKeys.cameraZoomBack: "",
                                                                                                        SpecificationKeys.cameraVideoResolutionBack: "UHD 4K (60 Klatek)",
                                                                                                        SpecificationKeys.connectivity: "5G, Bluetooth, Wi-FI 6",
                                                                                                        SpecificationKeys.inputs: "nanoSIM, USB-C",
                                                                                                        SpecificationKeys.fingerprintReader: "Tak",
                                                                                                        SpecificationKeys.faceReader: "Nie",
                                                                                                        SpecificationKeys.operatingSystem: "iPadOS 15",
                                                                                                        SpecificationKeys.weight: "",
                                                                                                        SpecificationKeys.additionalInfo: ""]],
                                                  unitsSold: 50,
                                                  isRecommended: true,
                                                  productQuantityAvailable: 170,
                                                  imagesURLs: ["https://mac-shop.pl/environment/cache/images/500_500_productGfx_14857.webp",
                                                               "https://www.orange.pl/medias/sys_master/root/images/h51/h41/11348699611166/ipad-air-5g-spacegray-front-OraProductZoom.png"]),
                                          Product(id: "BJll5oJjsBoq0tb6Ad8v",
                                                  name: "iPad Pro",
                                                  company: "Apple Inc.",
                                                  productDescription: "The ultimate iPad experience. Now with breakthrough M1 performance, a breathtaking XDR display, and blazing‑fast 5G wireless. Buckle up.",
                                                  category: .tablets,
                                                  priceForCurrency: ["USD": 899.99,
                                                                     "PLN": 4149.08,
                                                                     "CZK": 21501.53,
                                                                     "EUR": 885.47,
                                                                     "GBP": 771.98],
                                                  specification: [LanguageIdentifiers.english.rawValue: [SpecificationKeys.processor: "Apple M1 (8 cores, ARM)",
                                                                                                         SpecificationKeys.ramMemory: "16 GB",
                                                                                                         SpecificationKeys.massStorage: "2 TB",
                                                                                                         SpecificationKeys.displayType: "IPS, Liquid Retina",
                                                                                                         SpecificationKeys.displaySize: "11\"",
                                                                                                         SpecificationKeys.displayResolution: "2388 x 1668",
                                                                                                         SpecificationKeys.pixelDensity: "",
                                                                                                         SpecificationKeys.refreshRate: "120 Hz",
                                                                                                         SpecificationKeys.displayBrightness: "",
                                                                                                         SpecificationKeys.cameraPhotoResolutionFront: "12.0 Mpix",
                                                                                                         SpecificationKeys.cameraPhotoResolutionBack: "12.0 + 10.0 Mpix",
                                                                                                         SpecificationKeys.cameraZoomBack: "",
                                                                                                         SpecificationKeys.cameraVideoResolutionBack: "UHD 4K (60 FPS)",
                                                                                                         SpecificationKeys.connectivity: "Bluetooth, Wi-FI 6",
                                                                                                         SpecificationKeys.inputs: "Thunderbolt 4, Smart Connector",
                                                                                                         SpecificationKeys.fingerprintReader: "No",
                                                                                                         SpecificationKeys.faceReader: "Yes",
                                                                                                         SpecificationKeys.operatingSystem: "iPadOS 15",
                                                                                                         SpecificationKeys.weight: "",
                                                                                                         SpecificationKeys.additionalInfo: ""],
                                                                  
                                                                  LanguageIdentifiers.polish.rawValue: [SpecificationKeys.processor: "Apple M1 (8 rdzeni, ARM)",
                                                                                                        SpecificationKeys.ramMemory: "16 GB",
                                                                                                        SpecificationKeys.massStorage: "2 TB",
                                                                                                        SpecificationKeys.displayType: "IPS, Liquid Retina",
                                                                                                        SpecificationKeys.displaySize: "11\"",
                                                                                                        SpecificationKeys.displayResolution: "2388 x 1668",
                                                                                                        SpecificationKeys.pixelDensity: "",
                                                                                                        SpecificationKeys.refreshRate: "120 Hz",
                                                                                                        SpecificationKeys.displayBrightness: "",
                                                                                                        SpecificationKeys.cameraPhotoResolutionFront: "12.0 Mpix",
                                                                                                        SpecificationKeys.cameraPhotoResolutionBack: "12.0 + 10.0 Mpix",
                                                                                                        SpecificationKeys.cameraZoomBack: "",
                                                                                                        SpecificationKeys.cameraVideoResolutionBack: "UHD 4K (60 Klatek)",
                                                                                                        SpecificationKeys.connectivity: "Bluetooth, Wi-FI 6",
                                                                                                        SpecificationKeys.inputs: "Thunderbolt 4, Smart Connector",
                                                                                                        SpecificationKeys.fingerprintReader: "Nie",
                                                                                                        SpecificationKeys.faceReader: "Tak",
                                                                                                        SpecificationKeys.operatingSystem: "iPadOS 15",
                                                                                                        SpecificationKeys.weight: "",
                                                                                                        SpecificationKeys.additionalInfo: ""]],
                                                  unitsSold: 45,
                                                  isRecommended: true,
                                                  productQuantityAvailable: 150,
                                                  imagesURLs: ["https://www.orange.pl/medias/sys_master/root/images/hfa/h0a/9792549683230/ipad-pro-11-space-gray-front-OraProductZoom.png",
                                                               "https://toppng.com/uploads/preview/starting-at-ipad-pro-105-11569058975xz9kcmjfqn.png"]),
                                          Product(id: "v8yFH9voUUbMvYDXMX4o",
                                                  name: "MacBook Air",
                                                  company: "Apple Inc.",
                                                  productDescription: "There’s power in silence. Thanks to the efficiency of the M2 chip, MacBook Air can deliver amazing performance without a fan — so it stays completely silent no matter how intense the task.",
                                                  category: .laptops,
                                                  priceForCurrency: ["USD": 999.99,
                                                                     "PLN": 4610.09,
                                                                     "CZK": 23890.62,
                                                                     "EUR": 983.86,
                                                                     "GBP": 857.76],
                                                  specification: [LanguageIdentifiers.english.rawValue: [SpecificationKeys.processor: "Apple M2 (8 cores, ARM)",
                                                                                                         SpecificationKeys.ramMemory: "16 GB",
                                                                                                         SpecificationKeys.massStorage: "256 GB",
                                                                                                         SpecificationKeys.displayType: "IPS, Liquid Retina",
                                                                                                         SpecificationKeys.displaySize: "13.6\"",
                                                                                                         SpecificationKeys.displayResolution: "2560 x 1664",
                                                                                                         SpecificationKeys.pixelDensity: "",
                                                                                                         SpecificationKeys.refreshRate: "60 Hz",
                                                                                                         SpecificationKeys.displayBrightness: "",
                                                                                                         SpecificationKeys.cameraPhotoResolutionFront: "2.1 Mpix",
                                                                                                         SpecificationKeys.cameraPhotoResolutionBack: "",
                                                                                                         SpecificationKeys.cameraZoomBack: "",
                                                                                                         SpecificationKeys.cameraVideoResolutionBack: "",
                                                                                                         SpecificationKeys.connectivity: "Bluetooth, Wi-FI 6",
                                                                                                         SpecificationKeys.inputs: "Thunderbolt 4, MagSafe3, AUX",
                                                                                                         SpecificationKeys.fingerprintReader: "Yes",
                                                                                                         SpecificationKeys.faceReader: "No",
                                                                                                         SpecificationKeys.operatingSystem: "macOS Monterey",
                                                                                                         SpecificationKeys.weight: "",
                                                                                                         SpecificationKeys.additionalInfo: ""],
                                                                  
                                                                  LanguageIdentifiers.polish.rawValue: [SpecificationKeys.processor: "Apple M2 (8 rdzeni, ARM)",
                                                                                                        SpecificationKeys.ramMemory: "16 GB",
                                                                                                        SpecificationKeys.massStorage: "256 GB",
                                                                                                        SpecificationKeys.displayType: "IPS, Liquid Retina",
                                                                                                        SpecificationKeys.displaySize: "13.6\"",
                                                                                                        SpecificationKeys.displayResolution: "2560 x 1664",
                                                                                                        SpecificationKeys.pixelDensity: "",
                                                                                                        SpecificationKeys.refreshRate: "60 Hz",
                                                                                                        SpecificationKeys.displayBrightness: "",
                                                                                                        SpecificationKeys.cameraPhotoResolutionFront: "2.1 Mpix",
                                                                                                        SpecificationKeys.cameraPhotoResolutionBack: "",
                                                                                                        SpecificationKeys.cameraZoomBack: "",
                                                                                                        SpecificationKeys.cameraVideoResolutionBack: "",
                                                                                                        SpecificationKeys.connectivity: "Bluetooth, Wi-FI 6",
                                                                                                        SpecificationKeys.inputs: "Thunderbolt 4, MagSafe3, AUX",
                                                                                                        SpecificationKeys.fingerprintReader: "Tak",
                                                                                                        SpecificationKeys.faceReader: "Nie",
                                                                                                        SpecificationKeys.operatingSystem: "macOS Monterey",
                                                                                                        SpecificationKeys.weight: "",
                                                                                                        SpecificationKeys.additionalInfo: ""]],
                                                  unitsSold: 56,
                                                  productQuantityAvailable: 120,
                                                  imagesURLs: ["https://support.apple.com/library/APPLE/APPLECARE_ALLGEOS/SP825/macbookair.png",
                                                               "https://static.api.plenti.app/file/product/2900"]),
                                          Product(id: "uMIJzBU5wcwwfUMqsJ2C",
                                                  name: "MacBook Pro",
                                                  company: "Apple Inc.",
                                                  productDescription: "The most powerful MacBook Pro ever is here. With the blazing-fast M1 Pro or M1 Max chip — the first Apple silicon designed for pros — you get groundbreaking performance and amazing battery life. Add to that a stunning Liquid Retina XDR display, the best camera and audio ever in a Mac notebook, and all the ports you need. The first notebook of its kind, this MacBook Pro is a beast.",
                                                  category: .laptops,
                                                  priceForCurrency: ["USD": 999.99,
                                                                     "PLN": 6454.15,
                                                                     "CZK": 33446.97,
                                                                     "EUR": 1377.41,
                                                                     "GBP": 1200.87],
                                                  specification: [LanguageIdentifiers.english.rawValue: [SpecificationKeys.processor: "Apple M1 Pro",
                                                                                                         SpecificationKeys.ramMemory: "16 GB",
                                                                                                         SpecificationKeys.massStorage: "512 GB",
                                                                                                         SpecificationKeys.displayType: "mini-LED, Liquid Retina XDR",
                                                                                                         SpecificationKeys.displaySize: "16.2\"",
                                                                                                         SpecificationKeys.displayResolution: "3456 x 2234",
                                                                                                         SpecificationKeys.pixelDensity: "",
                                                                                                         SpecificationKeys.refreshRate: "120 Hz",
                                                                                                         SpecificationKeys.displayBrightness: "1000 cd/m²",
                                                                                                         SpecificationKeys.cameraPhotoResolutionFront: "2.1 Mpix",
                                                                                                         SpecificationKeys.cameraPhotoResolutionBack: "",
                                                                                                         SpecificationKeys.cameraZoomBack: "",
                                                                                                         SpecificationKeys.cameraVideoResolutionBack: "",
                                                                                                         SpecificationKeys.connectivity: "Bluetooth, Wi-FI 6",
                                                                                                         SpecificationKeys.inputs: "Thunderbolt 4, MagSafe3, AUX, HDMI, SD",
                                                                                                         SpecificationKeys.fingerprintReader: "Yes",
                                                                                                         SpecificationKeys.faceReader: "No",
                                                                                                         SpecificationKeys.operatingSystem: "macOS Monterey",
                                                                                                         SpecificationKeys.weight: "",
                                                                                                         SpecificationKeys.additionalInfo: ""],
                                                                  
                                                                  LanguageIdentifiers.polish.rawValue: [SpecificationKeys.processor: "Apple M1 Pro",
                                                                                                        SpecificationKeys.ramMemory: "16 GB",
                                                                                                        SpecificationKeys.massStorage: "512 GB",
                                                                                                        SpecificationKeys.displayType: "mini-LED, Liquid Retina XDR",
                                                                                                        SpecificationKeys.displaySize: "16.2\"",
                                                                                                        SpecificationKeys.displayResolution: "3456 x 2234",
                                                                                                        SpecificationKeys.pixelDensity: "",
                                                                                                        SpecificationKeys.refreshRate: "120 Hz",
                                                                                                        SpecificationKeys.displayBrightness: "1000 cd/m²",
                                                                                                        SpecificationKeys.cameraPhotoResolutionFront: "2.1 Mpix",
                                                                                                        SpecificationKeys.cameraPhotoResolutionBack: "",
                                                                                                        SpecificationKeys.cameraZoomBack: "",
                                                                                                        SpecificationKeys.cameraVideoResolutionBack: "",
                                                                                                        SpecificationKeys.connectivity: "Bluetooth, Wi-FI 6",
                                                                                                        SpecificationKeys.inputs: "Thunderbolt 4, MagSafe3, AUX, HDMI, SD",
                                                                                                        SpecificationKeys.fingerprintReader: "Tak",
                                                                                                        SpecificationKeys.faceReader: "Nie",
                                                                                                        SpecificationKeys.operatingSystem: "macOS Monterey",
                                                                                                        SpecificationKeys.weight: "",
                                                                                                        SpecificationKeys.additionalInfo: ""]],
                                                  unitsSold: 90,
                                                  isRecommended: true,
                                                  productQuantityAvailable: 100,
                                                  imagesURLs: ["https://w7.pngwing.com/pngs/279/698/png-transparent-macbookpro-apple-material-apple-macbook-pro-computer-product-in-kind.png",
                                                               "https://toppng.com/uploads/preview/macbook-pro-with-touch-bar-11562986819zyl2ty8n0m.png"]),
                                          Product(id: "IpD65nz0vKKgOUAzVDtq",
                                                  name: "iMac",
                                                  company: "Apple Inc.",
                                                  productDescription: "Say hello to the new iMac. Inspired by the best of Apple. Transformed by the M1 chip. Stands out in any space. Fits perfectly into your life.",
                                                  category: .computers,
                                                  priceForCurrency: ["USD": 1599.99,
                                                                     "PLN": 7376.18,
                                                                     "CZK": 38225.14,
                                                                     "EUR": 1574.18,
                                                                     "GBP": 1372.43],
                                                  specification: [LanguageIdentifiers.english.rawValue: [SpecificationKeys.processor: "Apple M1 (8 cores, ARM)",
                                                                                                         SpecificationKeys.ramMemory: "8 GB",
                                                                                                         SpecificationKeys.massStorage: "256 GB",
                                                                                                         SpecificationKeys.displayType: "LED, IPS, Retina",
                                                                                                         SpecificationKeys.displaySize: "23.5\"",
                                                                                                         SpecificationKeys.displayResolution: "4480 x 2520 (4.5K)",
                                                                                                         SpecificationKeys.pixelDensity: "",
                                                                                                         SpecificationKeys.refreshRate: "60 Hz",
                                                                                                         SpecificationKeys.displayBrightness: "",
                                                                                                         SpecificationKeys.cameraPhotoResolutionFront: "",
                                                                                                         SpecificationKeys.cameraPhotoResolutionBack: "",
                                                                                                         SpecificationKeys.cameraZoomBack: "",
                                                                                                         SpecificationKeys.cameraVideoResolutionBack: "",
                                                                                                         SpecificationKeys.connectivity: "Bluetooth, Wi-FI 6",
                                                                                                         SpecificationKeys.inputs: "Thunderbolt 4, DC-in (power input)",
                                                                                                         SpecificationKeys.fingerprintReader: "No",
                                                                                                         SpecificationKeys.faceReader: "No",
                                                                                                         SpecificationKeys.operatingSystem: "macOS Big Sur",
                                                                                                         SpecificationKeys.weight: "",
                                                                                                         SpecificationKeys.additionalInfo: ""],
                                                                  
                                                                  LanguageIdentifiers.polish.rawValue: [SpecificationKeys.processor: "Apple M1 (8 rdzeni, ARM)",
                                                                                                        SpecificationKeys.ramMemory: "8 GB",
                                                                                                        SpecificationKeys.massStorage: "256 GB",
                                                                                                        SpecificationKeys.displayType: "LED, IPS, Retina",
                                                                                                        SpecificationKeys.displaySize: "23.5\"",
                                                                                                        SpecificationKeys.displayResolution: "4480 x 2520 (4.5K)",
                                                                                                        SpecificationKeys.pixelDensity: "",
                                                                                                        SpecificationKeys.refreshRate: "60 Hz",
                                                                                                        SpecificationKeys.displayBrightness: "",
                                                                                                        SpecificationKeys.cameraPhotoResolutionFront: "",
                                                                                                        SpecificationKeys.cameraPhotoResolutionBack: "",
                                                                                                        SpecificationKeys.cameraZoomBack: "",
                                                                                                        SpecificationKeys.cameraVideoResolutionBack: "",
                                                                                                        SpecificationKeys.connectivity: "Bluetooth, Wi-FI 6",
                                                                                                        SpecificationKeys.inputs: "Thunderbolt 4, DC-in (wejście zasilania)",
                                                                                                        SpecificationKeys.fingerprintReader: "Nie",
                                                                                                        SpecificationKeys.faceReader: "Nie",
                                                                                                        SpecificationKeys.operatingSystem: "macOS Big Sur",
                                                                                                        SpecificationKeys.weight: "",
                                                                                                        SpecificationKeys.additionalInfo: ""]],
                                                  unitsSold: 20,
                                                  productQuantityAvailable: 80,
                                                  imagesURLs: ["https://images.macrumors.com/t/ylfMwnTtxo7SQpK6767ULmfZarY=/1600x1200/smart/article-new/2013/09/imac-m1-blue-isolated-16x9-500k.png",
                                                               "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/M1_iMac_vector.svg/1200px-M1_iMac_vector.svg.png"]),
                                          Product(id: "qxfRHQx4eQF748wBPN7B",
                                                  name: "Mac Pro",
                                                  company: "Apple Inc.",
                                                  productDescription: "Power to change everything. Say hello to a Mac that is extreme in every way. With the greatest performance, expansion, and configurability yet, it is a system created to let a wide range of professionals push the limits of what is possible.",
                                                  category: .computers,
                                                  priceForCurrency: ["USD": 2599.99,
                                                                     "PLN": 11986.32,
                                                                     "CZK": 62116.00,
                                                                     "EUR": 2558.05,
                                                                     "GBP": 2230.20],
                                                  specification: [LanguageIdentifiers.english.rawValue: [SpecificationKeys.processor: "Intel Xeon W-3223 (8 cores, 16 threads, 3.50- 4.00 GHz, 16.50 MB cache)",
                                                                                                         SpecificationKeys.ramMemory: "32 GB (DIMM DDR4, 2666 MHz)",
                                                                                                         SpecificationKeys.massStorage: "512 GB SSD",
                                                                                                         SpecificationKeys.displayType: "mini-LED, Liquid Retina XDR",
                                                                                                         SpecificationKeys.displaySize: "",
                                                                                                         SpecificationKeys.displayResolution: "",
                                                                                                         SpecificationKeys.pixelDensity: "",
                                                                                                         SpecificationKeys.refreshRate: "",
                                                                                                         SpecificationKeys.displayBrightness: "",
                                                                                                         SpecificationKeys.cameraPhotoResolutionFront: "",
                                                                                                         SpecificationKeys.cameraPhotoResolutionBack: "",
                                                                                                         SpecificationKeys.cameraZoomBack: "",
                                                                                                         SpecificationKeys.cameraVideoResolutionBack: "",
                                                                                                         SpecificationKeys.connectivity: "Bluetooth, Wi-FI 5, LAN 10 Gbps",
                                                                                                         SpecificationKeys.inputs: "USB 3.2 Gen. 1, Thunderbolt 3, AUX, RJ-45 (LAN), HDMI, AC-in (power input)",
                                                                                                         SpecificationKeys.fingerprintReader: "No",
                                                                                                         SpecificationKeys.faceReader: "No",
                                                                                                         SpecificationKeys.operatingSystem: "macOS Catalina",
                                                                                                         SpecificationKeys.weight: "",
                                                                                                         SpecificationKeys.additionalInfo: ""],
                                                                  
                                                                  LanguageIdentifiers.polish.rawValue: [SpecificationKeys.processor: "Intel Xeon W-3223 (8 rdzeni, 16 wątków, 3.50- 4.00 GHz, 16.50 MB cache)",
                                                                                                        SpecificationKeys.ramMemory: "32 GB (DIMM DDR4, 2666 MHz)",
                                                                                                        SpecificationKeys.massStorage: "256 GB SSD",
                                                                                                        SpecificationKeys.displayType: "IPS, Liquid Retina",
                                                                                                        SpecificationKeys.displaySize: "",
                                                                                                        SpecificationKeys.displayResolution: "",
                                                                                                        SpecificationKeys.pixelDensity: "",
                                                                                                        SpecificationKeys.refreshRate: "",
                                                                                                        SpecificationKeys.displayBrightness: "",
                                                                                                        SpecificationKeys.cameraPhotoResolutionFront: "",
                                                                                                        SpecificationKeys.cameraPhotoResolutionBack: "",
                                                                                                        SpecificationKeys.cameraZoomBack: "",
                                                                                                        SpecificationKeys.cameraVideoResolutionBack: "",
                                                                                                        SpecificationKeys.connectivity: "Bluetooth, Wi-FI 5, LAN 10 Gbps",
                                                                                                        SpecificationKeys.inputs: "USB 3.2 Gen. 1, Thunderbolt 3, AUX, RJ-45 (LAN), HDMI, AC-in (wejście zasilania)",
                                                                                                        SpecificationKeys.fingerprintReader: "Nie",
                                                                                                        SpecificationKeys.faceReader: "Nie",
                                                                                                        SpecificationKeys.operatingSystem: "macOS Catalina",
                                                                                                        SpecificationKeys.weight: "",
                                                                                                        SpecificationKeys.additionalInfo: ""]],
                                                  unitsSold: 25,
                                                  productQuantityAvailable: 60,
                                                  imagesURLs: ["https://imagazine.pl/wp-content/uploads/2019/06/Mac-Pro-2019-mid-and-Pro-Display-XDR-10.png",
                                                               "https://macmedic.com.au/wp-content/uploads/2021/07/MacMedic-Sydney-Mac_Pro_2-up_Screen__USEN.png"]),
                                          Product(id: "veArtsZlHvLVmJgB1Eb2",
                                                  name: "Apple Watch Series 7",
                                                  company: "Apple Inc.",
                                                  productDescription: "The larger display enhances the entire experience, making Apple Watch easier to use and read. Series 7 represents our biggest and brightest thinking.",
                                                  category: .watches,
                                                  priceForCurrency: ["USD": 2599.99,
                                                                     "PLN": 2305.02,
                                                                     "CZK": 11945.19,
                                                                     "EUR": 491.92,
                                                                     "GBP": 428.87],
                                                  specification: [LanguageIdentifiers.english.rawValue: [SpecificationKeys.processor: "",
                                                                                                         SpecificationKeys.ramMemory: "",
                                                                                                         SpecificationKeys.massStorage: "",
                                                                                                         SpecificationKeys.displayType: "OLED, LTPO, Retina",
                                                                                                         SpecificationKeys.displaySize: "45 mm",
                                                                                                         SpecificationKeys.displayResolution: "",
                                                                                                         SpecificationKeys.pixelDensity: "",
                                                                                                         SpecificationKeys.refreshRate: "",
                                                                                                         SpecificationKeys.displayBrightness: "",
                                                                                                         SpecificationKeys.cameraPhotoResolutionFront: "",
                                                                                                         SpecificationKeys.cameraPhotoResolutionBack: "",
                                                                                                         SpecificationKeys.cameraZoomBack: "",
                                                                                                         SpecificationKeys.cameraVideoResolutionBack: "",
                                                                                                         SpecificationKeys.connectivity: "Bluetooth, Wi-FI, 4G (LTE) eSIM, NFC",
                                                                                                         SpecificationKeys.inputs: "",
                                                                                                         SpecificationKeys.fingerprintReader: "No",
                                                                                                         SpecificationKeys.faceReader: "No",
                                                                                                         SpecificationKeys.operatingSystem: "watchOS 8",
                                                                                                         SpecificationKeys.weight: "38.8 g",
                                                                                                         SpecificationKeys.additionalInfo: "Wireless Synchronization, Mobile App Integration, Wireless Charging, Touchable Digital Crown, Watch Face Personalization"],
                                                                  
                                                                  LanguageIdentifiers.polish.rawValue: [SpecificationKeys.processor: "",
                                                                                                        SpecificationKeys.ramMemory: "",
                                                                                                        SpecificationKeys.massStorage: "",
                                                                                                        SpecificationKeys.displayType: "OLED, LTPO, Retina",
                                                                                                        SpecificationKeys.displaySize: "45 mm",
                                                                                                        SpecificationKeys.displayResolution: "",
                                                                                                        SpecificationKeys.pixelDensity: "",
                                                                                                        SpecificationKeys.refreshRate: "",
                                                                                                        SpecificationKeys.displayBrightness: "1",
                                                                                                        SpecificationKeys.cameraPhotoResolutionFront: "",
                                                                                                        SpecificationKeys.cameraPhotoResolutionBack: "",
                                                                                                        SpecificationKeys.cameraZoomBack: "",
                                                                                                        SpecificationKeys.cameraVideoResolutionBack: "",
                                                                                                        SpecificationKeys.connectivity: "Bluetooth, Wi-FI, 4G (LTE) eSIM, NFC",
                                                                                                        SpecificationKeys.inputs: "",
                                                                                                        SpecificationKeys.fingerprintReader: "Nie",
                                                                                                        SpecificationKeys.faceReader: "Nie",
                                                                                                        SpecificationKeys.operatingSystem: "watchOS 8",
                                                                                                        SpecificationKeys.weight: "38.8 g",
                                                                                                        SpecificationKeys.additionalInfo: "Bezprzewodowa synchronizacja, Integracja z aplikacją mobilną, Bezprzewodowe ładowanie, Dotykowy Digital Crown, Możliwość indywidualnego dostosowania wyglądu tarczy zegarka"]],
                                                  unitsSold: 87,
                                                  isRecommended: true,
                                                  productQuantityAvailable: 50,
                                                  imagesURLs: ["https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/MN2D3_VW_PF+watch-45-alum-starlight-cell-7s_VW_PF_WF_SI?wid=2000&hei=2000&fmt=png-alpha&.v=1645128285436,1631661830000",
                                                       "https://cdn.shopify.com/s/files/1/0613/5683/5009/products/series7-480_grande.png?v=1653135860"]),
                                          Product(id: "7vHPvsjhC2N3DszzpejX",
                                                  name: "AirPods Pro",
                                                  company: "US TOT LTD.",
                                                  productDescription: "AirPods Pro are the only in-ear headphones with Active Noise Cancellation that continuously adapts to the geometry of your ear and the fit of the ear tips — blocking out the world so you can focus on what you’re listening to.",
                                                  category: .accessories,
                                                  priceForCurrency: ["USD": 249.99,
                                                                     "PLN": 1152.48,
                                                                     "CZK": 5972.47,
                                                                     "EUR": 245.95,
                                                                     "GBP": 214.43],
                                                  specification: [LanguageIdentifiers.english.rawValue: [SpecificationKeys.processor: "",
                                                                                                         SpecificationKeys.ramMemory: "",
                                                                                                         SpecificationKeys.massStorage: "",
                                                                                                         SpecificationKeys.displayType: "",
                                                                                                         SpecificationKeys.displaySize: "",
                                                                                                         SpecificationKeys.displayResolution: "",
                                                                                                         SpecificationKeys.pixelDensity: "",
                                                                                                         SpecificationKeys.refreshRate: "",
                                                                                                         SpecificationKeys.displayBrightness: "",
                                                                                                         SpecificationKeys.cameraPhotoResolutionFront: "",
                                                                                                         SpecificationKeys.cameraPhotoResolutionBack: "",
                                                                                                         SpecificationKeys.cameraZoomBack: "",
                                                                                                         SpecificationKeys.cameraVideoResolutionBack: "",
                                                                                                         SpecificationKeys.connectivity: "Bluetooth 5.0",
                                                                                                         SpecificationKeys.inputs: "Lightning",
                                                                                                         SpecificationKeys.fingerprintReader: "No",
                                                                                                         SpecificationKeys.faceReader: "No",
                                                                                                         SpecificationKeys.operatingSystem: "",
                                                                                                         SpecificationKeys.weight: "5.4 g (single pod), 45.6 g (etui)",
                                                                                                         SpecificationKeys.additionalInfo: ""],
                                                                  
                                                                  LanguageIdentifiers.polish.rawValue: [SpecificationKeys.processor: "",
                                                                                                        SpecificationKeys.ramMemory: "",
                                                                                                        SpecificationKeys.massStorage: "",
                                                                                                        SpecificationKeys.displayType: "",
                                                                                                        SpecificationKeys.displaySize: "",
                                                                                                        SpecificationKeys.displayResolution: "",
                                                                                                        SpecificationKeys.pixelDensity: "",
                                                                                                        SpecificationKeys.refreshRate: "",
                                                                                                        SpecificationKeys.displayBrightness: "",
                                                                                                        SpecificationKeys.cameraPhotoResolutionFront: "",
                                                                                                        SpecificationKeys.cameraPhotoResolutionBack: "",
                                                                                                        SpecificationKeys.cameraZoomBack: "",
                                                                                                        SpecificationKeys.cameraVideoResolutionBack: "",
                                                                                                        SpecificationKeys.connectivity: "Bluetooth 5.0",
                                                                                                        SpecificationKeys.inputs: "Lightning",
                                                                                                        SpecificationKeys.fingerprintReader: "Nie",
                                                                                                        SpecificationKeys.faceReader: "Nie",
                                                                                                        SpecificationKeys.operatingSystem: "",
                                                                                                        SpecificationKeys.weight: "5.4 g (jedna słuchawka), 45.6 g (etui)",
                                                                                                        SpecificationKeys.additionalInfo: ""]],
                                                  unitsSold: 64,
                                                  isRecommended: true,
                                                  productQuantityAvailable: 30,
                                                  imagesURLs: ["https://www.freepnglogos.com/uploads/airpods-png/airpods-apple-news-articles-stories-trends-for-today-14.png",
                                                               "https://i.pinimg.com/originals/cf/8a/5e/cf8a5e66b8641f3b1b11e364e84fb093.png"]),
                                          Product(id: "K3UWdDrCQD6fVJgJk6dX",
                                                  name: "AirPods Max",
                                                  company: "Apple Inc.",
                                                  productDescription: "Introducing AirPods Max — a perfect balance of exhilarating high-fidelity audio and the effortless magic of AirPods. The ultimate personal listening experience is here.",
                                                  category: .accessories,
                                                  priceForCurrency: ["USD": 249.99,
                                                                     "PLN": 1152.48,
                                                                     "CZK": 5972.47,
                                                                     "EUR": 245.95,
                                                                     "GBP": 214.43],
                                                  specification: [LanguageIdentifiers.english.rawValue: [SpecificationKeys.processor: "",
                                                                                                         SpecificationKeys.ramMemory: "",
                                                                                                         SpecificationKeys.massStorage: "",
                                                                                                         SpecificationKeys.displayType: "",
                                                                                                         SpecificationKeys.displaySize: "",
                                                                                                         SpecificationKeys.displayResolution: "",
                                                                                                         SpecificationKeys.pixelDensity: "",
                                                                                                         SpecificationKeys.refreshRate: "",
                                                                                                         SpecificationKeys.displayBrightness: "",
                                                                                                         SpecificationKeys.cameraPhotoResolutionFront: "",
                                                                                                         SpecificationKeys.cameraPhotoResolutionBack: "",
                                                                                                         SpecificationKeys.cameraZoomBack: "",
                                                                                                         SpecificationKeys.cameraVideoResolutionBack: "",
                                                                                                         SpecificationKeys.connectivity: "Bluetooth 5.0",
                                                                                                         SpecificationKeys.inputs: "Lightning",
                                                                                                         SpecificationKeys.fingerprintReader: "No",
                                                                                                         SpecificationKeys.faceReader: "No",
                                                                                                         SpecificationKeys.operatingSystem: "",
                                                                                                         SpecificationKeys.weight: "5.4 g (single pod), 45.6 g (etui)",
                                                                                                         SpecificationKeys.additionalInfo: "Touchable control panel, LED indicator, Water resistant (IPX4), Calls answering, Accelerometer with speech recognition, Music control, Two optical sensors, Voice commands, Force Touch sensor, Etui with wireless charging function, Automatic pairing, Double microphone system"],
                                                                  
                                                                  LanguageIdentifiers.polish.rawValue: [SpecificationKeys.processor: "",
                                                                                                        SpecificationKeys.ramMemory: "",
                                                                                                        SpecificationKeys.massStorage: "",
                                                                                                        SpecificationKeys.displayType: "",
                                                                                                        SpecificationKeys.displaySize: "",
                                                                                                        SpecificationKeys.displayResolution: "",
                                                                                                        SpecificationKeys.pixelDensity: "",
                                                                                                        SpecificationKeys.refreshRate: "",
                                                                                                        SpecificationKeys.displayBrightness: "",
                                                                                                        SpecificationKeys.cameraPhotoResolutionFront: "",
                                                                                                        SpecificationKeys.cameraPhotoResolutionBack: "",
                                                                                                        SpecificationKeys.cameraZoomBack: "",
                                                                                                        SpecificationKeys.cameraVideoResolutionBack: "",
                                                                                                        SpecificationKeys.connectivity: "Bluetooth 5.0",
                                                                                                        SpecificationKeys.inputs: "Lightning",
                                                                                                        SpecificationKeys.fingerprintReader: "Nie",
                                                                                                        SpecificationKeys.faceReader: "Nie",
                                                                                                        SpecificationKeys.operatingSystem: "",
                                                                                                        SpecificationKeys.weight: "5.4 g (jedna słuchawka), 45.6 g (etui)",
                                                                                                        SpecificationKeys.additionalInfo: "Dotykowy panel sterowania, Wskaźnik LED, Wodoszczelność (IPX4), Odbieranie połączeń, Przyspieszeniomierz wykrywający mowę, Sterowanie muzyką, Dwa czujniki optyczne, Sterowanie głosem, Czujnik nacisku, Etui ładujące z funkcją ładowania bezprzewodowego, Automatyczne parowanie, Podwójny układ mikrofonów"]],
                                                  unitsSold: 34,
                                                  productQuantityAvailable: 20,
                                                  imagesURLs: ["https://www.apple.com/v/airpods-max/e/images/overview/hero__gnfk5g59t0qe_xlarge.png",
                                                               "https://www.apple.com/v/airpods-max/e/images/overview/design_hero_cups__ddp0h9jo76gm_large.png"]),
                                          Product(id: "cKuK5oxw6WaHWaMmxkyW",
                                                  name: "Apple TV 4K",
                                                  company: "Apple Inc.",
                                                  productDescription: "Apple TV 4K brings the best of TV together with your favorite Apple devices and services — in a powerful experience that will transform your living room.",
                                                  category: .accessories,
                                                  priceForCurrency: ["USD": 399.99,
                                                                     "PLN": 1844.01,
                                                                     "CZK": 9556.10,
                                                                     "EUR": 393.53,
                                                                     "GBP": 343.10],
                                                  specification: [LanguageIdentifiers.english.rawValue: [SpecificationKeys.processor: "Apple A12",
                                                                                                         SpecificationKeys.ramMemory: "",
                                                                                                         SpecificationKeys.massStorage: "64 GB",
                                                                                                         SpecificationKeys.displayType: "",
                                                                                                         SpecificationKeys.displaySize: "",
                                                                                                         SpecificationKeys.displayResolution: "",
                                                                                                         SpecificationKeys.pixelDensity: "",
                                                                                                         SpecificationKeys.refreshRate: "",
                                                                                                         SpecificationKeys.displayBrightness: "",
                                                                                                         SpecificationKeys.cameraPhotoResolutionFront: "",
                                                                                                         SpecificationKeys.cameraPhotoResolutionBack: "",
                                                                                                         SpecificationKeys.cameraZoomBack: "",
                                                                                                         SpecificationKeys.cameraVideoResolutionBack: "",
                                                                                                         SpecificationKeys.connectivity: "Bluetooth, Wi-FI 6, IR Receiver",
                                                                                                         SpecificationKeys.inputs: "HDMI, RJ45, DC-in (power input)",
                                                                                                         SpecificationKeys.fingerprintReader: "No",
                                                                                                         SpecificationKeys.faceReader: "No",
                                                                                                         SpecificationKeys.operatingSystem: "tvOS",
                                                                                                         SpecificationKeys.weight: "425 g",
                                                                                                         SpecificationKeys.additionalInfo: "Photo library, Built-in microphone, Voice commands, AppStore access, Dolby Atmos support, Dolby Vision support"],
                                                                  
                                                                  LanguageIdentifiers.polish.rawValue: [SpecificationKeys.processor: "Apple A12",
                                                                                                        SpecificationKeys.ramMemory: "",
                                                                                                        SpecificationKeys.massStorage: "64 GB",
                                                                                                        SpecificationKeys.displayType: "",
                                                                                                        SpecificationKeys.displaySize: "",
                                                                                                        SpecificationKeys.displayResolution: "",
                                                                                                        SpecificationKeys.pixelDensity: "",
                                                                                                        SpecificationKeys.refreshRate: "",
                                                                                                        SpecificationKeys.displayBrightness: "",
                                                                                                        SpecificationKeys.cameraPhotoResolutionFront: "",
                                                                                                        SpecificationKeys.cameraPhotoResolutionBack: "",
                                                                                                        SpecificationKeys.cameraZoomBack: "",
                                                                                                        SpecificationKeys.cameraVideoResolutionBack: "",
                                                                                                        SpecificationKeys.connectivity: "Bluetooth, Wi-FI 6, Odbiornik IR",
                                                                                                        SpecificationKeys.inputs: "HDMI, RJ45, DC-in (wejście zasilania)",
                                                                                                        SpecificationKeys.fingerprintReader: "Nie",
                                                                                                        SpecificationKeys.faceReader: "Nie",
                                                                                                        SpecificationKeys.operatingSystem: "tvOS",
                                                                                                        SpecificationKeys.weight: "425 g",
                                                                                                        SpecificationKeys.additionalInfo: "Przeglądanie zdjęć, Wbudowany mikrofon, Obsługa głosowa, Dostęp do AppStore, Wsparcie dla technologii Dolby Atmos, Wsparcie dla technologii Dolby Vision"]],
                                                  unitsSold: 15,
                                                  productQuantityAvailable: 0,
                                                  imagesURLs: ["https://w7.pngwing.com/pngs/326/890/png-transparent-apple-tv-4k-apple-tv-4th-generation-4k-resolution-new-autumn-products-television-electronics-media-player-thumbnail.png",
                                                               "https://w7.pngwing.com/pngs/393/564/png-transparent-apple-tv-4th-generation-television-apple-tv-4k-creative-certificate-material-television-electronics-electronic-device-thumbnail.png"])]
}
